name: validate-push

# Environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'Evergreen/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: windows-2022
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run Pester tests
      - name: Run Pester tests
        shell: powershell
        run: |
          . .\ci\Install.ps1
          . .\ci\Tests.ps1
